import { ENDLESS, newEndless, type EndlessSave } from './endless';
import { BALANCE, LEVELS, UPGRADES, type Resource, type UpgradeId } from './data';
import { clampSfxVolume } from './audio';
export type EquipmentSlot = 'weapon' | 'armor' | 'charm';
export interface Base { name: string; upgrades: Record<UpgradeId, number>; hp: number; wave: number }
export interface Save { endless: EndlessSave; version: 1; level: number; xp: number; gold: number; supplies: number; materials: Record<Resource, number>; equipment: Record<EquipmentSlot, number>; bases: Base[]; activeBase: number; discoveries: number[]; bosses: number[]; camps: number[]; visited: number[]; expeditionUnlocked: boolean; kills: number; elapsed: number; nextRaid: number; raidPending: boolean; raids: number; raidTime: number; skill: number; settings: { particles: boolean; shake: boolean; sfxVolume: number; sfxMuted: boolean }; completed: boolean }
export const SAVE_KEY = 'outpost-horizons-v1';
export function newBase(name: string): Base { return { name, upgrades: Object.fromEntries(UPGRADES.map(u => [u.id, 0])) as Record<UpgradeId, number>, hp: BALANCE.baseHealth, wave: 0 }; }
export function newSave(): Save { return { endless: newEndless(), version: 1, level: 1, xp: 0, gold: 35, supplies: 0, materials: { wood: 0, iron: 0, crystal: 0 }, equipment: { weapon: 0, armor: 0, charm: 0 }, bases: [newBase('緑風の野営地')], activeBase: 0, discoveries: [], bosses: [], camps: [], visited: [0], expeditionUnlocked: false, kills: 0, elapsed: 0, nextRaid: BALANCE.raidInterval, raidPending: false, raids: 0, raidTime: BALANCE.raidCountdown, skill: 0, settings: { particles: true, shake: true, sfxVolume: .55, sfxMuted: false }, completed: false }; }
export function currentBase(s: Save) { return s.bases[s.activeBase]; }
export function baseMaxHp(b: Base) { return BALANCE.baseHealth + b.upgrades.base * BALANCE.baseHealthPerLevel + b.upgrades.wall * BALANCE.wallHealth; }
export function supplyAttackBonus(s: Save) { return BALANCE.progression.supplyAttack + currentBase(s).upgrades.base * BALANCE.progression.supplyPerBase + s.bases[0].upgrades.training * BALANCE.progression.supplyPerTraining; }
export function heroStats(s: Save, prepared = false) { const u = s.bases[0].upgrades; const row = LEVELS[s.level - 1]; const b = BALANCE.upgrades, e = BALANCE.equipment; return { hp: Math.round(row.hp * (1 + u.health * b.health + s.equipment.armor * e.armor)), attack: row.attack * (1 + u.attack * b.attack + s.equipment.weapon * e.weapon + u.forge * b.forge) * (1 + Math.floor(s.equipment.weapon / BALANCE.progression.weaponMilestone) * BALANCE.progression.weaponMilestoneBonus) * (prepared ? 1 + supplyAttackBonus(s) : 1), interval: BALANCE.heroInterval / (1 + u.speed * b.speed), range: BALANCE.heroRange + u.range * b.range, speed: BALANCE.heroSpeed * (1 + u.move * b.move), damageReduction: Math.floor(s.equipment.armor / BALANCE.progression.weaponMilestone) * BALANCE.progression.armorMilestoneReduction, crit: e.critBase + s.equipment.charm * e.charmCrit, xpBonus: 1 + s.equipment.charm * e.charmXp }; }
export function gainXp(s: Save, amount: number) { s.xp += Math.round(amount * heroStats(s).xpBonus); const before = s.level; while (s.level < BALANCE.maxLevel && s.xp >= LEVELS[s.level - 1].xp) { s.xp -= LEVELS[s.level - 1].xp; s.level++; } if (s.level === BALANCE.maxLevel) s.xp = 0; return s.level - before; }
export function upgradeLevel(s: Save, id: UpgradeId) { return ['attack', 'speed', 'range', 'health', 'move', 'training', 'forge'].includes(id) ? s.bases[0].upgrades[id] : currentBase(s).upgrades[id]; }
export function upgradeCost(s: Save, id: UpgradeId) { const u = UPGRADES.find(u => u.id === id)!; const lv = upgradeLevel(s, id); return { gold: Math.round(u.cost * u.growth ** lv * (s.activeBase === 1 && !['attack', 'speed', 'range', 'health', 'move', 'training', 'forge'].includes(id) ? BALANCE.secondBase.discount : 1)), material: lv >= BALANCE.progression.advancedMaterialFrom ? 'crystal' as Resource : u.material, count: lv >= BALANCE.progression.advancedMaterialFrom ? BALANCE.progression.advancedMaterialBase + (lv - BALANCE.progression.advancedMaterialFrom) * BALANCE.progression.advancedMaterialGrowth : u.material ? Math.round((5 + lv * 4) * (s.discoveries.includes(4) && id === 'storage' ? .6 : 1)) : 0 }; }
export function upgradeLock(s: Save, id: UpgradeId): string | null { const u = UPGRADES.find(u => u.id === id)!; if (upgradeLevel(s, id) >= u.max) return '最大レベル'; if (u.unlock !== undefined && !s.discoveries.includes(u.unlock)) return '遠征の発見で解禁'; if (id === 'soldiers' && upgradeLevel(s, id) >= 1 + (s.discoveries.includes(0) ? 2 : 0) + (s.discoveries.includes(2) ? 3 : 0) + (s.discoveries.includes(7) ? 4 : 0)) return '生存者の救出で枠を拡張'; if (upgradeLevel(s, id) >= 10 && !s.discoveries.includes(9)) return '汚染地帯の結晶で解放'; return null; }
export function buyUpgrade(s: Save, id: UpgradeId) { if (upgradeLock(s, id)) return false; const c = upgradeCost(s, id); if (s.gold < c.gold || (c.material && s.materials[c.material] < c.count)) return false; s.gold -= c.gold; if (c.material) s.materials[c.material] -= c.count; const permanent = ['attack', 'speed', 'range', 'health', 'move', 'training', 'forge'].includes(id); (permanent ? s.bases[0] : currentBase(s)).upgrades[id]++; if (id === 'base' || id === 'wall') currentBase(s).hp = Math.min(baseMaxHp(currentBase(s)), currentBase(s).hp + (id === 'base' ? BALANCE.baseHealthPerLevel : BALANCE.wallHealth)); return true; }
export function equipmentCost(s: Save, slot: EquipmentSlot) { return Math.round(BALANCE.equipmentBaseCost * BALANCE.equipmentGrowth ** s.equipment[slot] * (1 - Math.min(BALANCE.progression.maxForgeDiscount, s.bases[0].upgrades.forge * BALANCE.progression.forgeDiscount))); }
export function equipmentCap(s: Save) { return s.discoveries.includes(8) ? 18 : s.discoveries.includes(6) ? 14 : s.discoveries.includes(3) ? 12 : 4; }
export function buyEquipment(s: Save, slot: EquipmentSlot) { const n = s.equipment[slot]; const cost = equipmentCost(s, slot); const material: Resource = n >= 12 ? 'crystal' : n >= 4 ? 'iron' : 'wood'; if (n >= equipmentCap(s) || s.gold < cost || s.materials[material] < 4 + n * 2) return false; s.gold -= cost; s.materials[material] -= 4 + n * 2; s.equipment[slot]++; return true; }
export function buildSecondBase(s: Save) { if (!s.discoveries.includes(5) || s.bases.length > 1 || s.gold < BALANCE.secondBase.gold || s.materials.iron < BALANCE.secondBase.iron) return false; s.gold -= BALANCE.secondBase.gold; s.materials.iron -= BALANCE.secondBase.iron; s.bases.push(newBase('赤砂の前哨基地')); return true; }
export function skillCost(s: Save) { return { gold: BALANCE.skillUpgrade.baseCost * (s.skill + 1) ** 2, crystal: s.skill >= BALANCE.skillUpgrade.crystalFrom ? s.skill * BALANCE.skillUpgrade.crystalPerLevel : 0 }; }
export function buySkill(s: Save) { const c = skillCost(s); if (s.skill >= BALANCE.skillUpgrade.max || s.gold < c.gold || s.materials.crystal < c.crystal) return false; s.gold -= c.gold; s.materials.crystal -= c.crystal; s.skill++; return true; }
const number = (v: unknown, fallback: number, min: number, max: number) => typeof v === 'number' && Number.isFinite(v) ? Math.max(min, Math.min(max, v)) : fallback;
export function parseSave(raw: string | null): Save { if (!raw) return newSave(); try { const a = JSON.parse(raw); if (a?.version !== 1 || !Array.isArray(a.bases) || a.bases.length < 1) return newSave(); const s = newSave(); for (const key of ['level', 'xp', 'gold', 'supplies', 'kills', 'elapsed', 'nextRaid', 'raidTime', 'skill', 'raids'] as const) s[key] = number(a[key], s[key], 0, 1e12); s.level = Math.floor(number(a.level, 1, 1, 55)); s.skill = Math.floor(number(a.skill, 0, 0, 8)); s.supplies = Math.floor(number(a.supplies, 0, 0, BALANCE.progression.supplyCap)); for (const key of ['wood', 'iron', 'crystal'] as const) s.materials[key] = number(a.materials?.[key], 0, 0, 1e12); for (const key of ['weapon', 'armor', 'charm'] as const) s.equipment[key] = Math.floor(number(a.equipment?.[key], 0, 0, 18)); s.bases = a.bases.slice(0, 2).map((b: Base, i: number) => { const base = newBase(i ? '赤砂の前哨基地' : '緑風の野営地'); for (const u of UPGRADES) base.upgrades[u.id] = Math.floor(number(b?.upgrades?.[u.id], 0, 0, u.max)); base.hp = number(b?.hp, BALANCE.baseHealth, 1, baseMaxHp(base)); base.wave = Math.floor(number(b?.wave, 0, 0, 1e6)); return base; }); s.activeBase = Math.floor(number(a.activeBase, 0, 0, s.bases.length - 1)); for (const key of ['discoveries', 'bosses', 'camps', 'visited'] as const) s[key] = Array.isArray(a[key]) ? [...new Set<number>(a[key].filter((n: unknown) => typeof n === 'number' && Number.isInteger(n) && n >= 0 && n <= 10))] : []; for (const key of ['expeditionUnlocked', 'raidPending', 'completed'] as const) s[key] = a[key] === true; s.raidTime = number(a.raidTime, 75, 0, 75); for (const key of ['bestWave', 'bestDanger', 'mastery'] as const) s.endless[key] = Math.floor(number(a.endless?.[key], 0, 0, Number.MAX_SAFE_INTEGER)); s.endless.shards = number(a.endless?.shards, 0, 0, ENDLESS.safeValue); for (const key of ['gold', 'wood', 'iron', 'crystal', 'shards', 'rareDrops'] as const) s.endless.rewards[key] = number(a.endless?.rewards?.[key], 0, 0, ENDLESS.safeValue); s.gold = number(a.gold, s.gold, 0, ENDLESS.safeValue); for (const key of ['wood', 'iron', 'crystal'] as const) s.materials[key] = number(a.materials?.[key], 0, 0, ENDLESS.safeValue); s.settings = { particles: a.settings?.particles !== false, shake: a.settings?.shake !== false, sfxVolume: clampSfxVolume(a.settings?.sfxVolume), sfxMuted: a.settings?.sfxMuted === true }; return s; } catch { return newSave(); } }
export function loadSave() { try { return parseSave(localStorage.getItem(SAVE_KEY)); } catch { return newSave(); } }
