import EndlessPanel from './EndlessPanel';
import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { ArrowDownToLine, ArrowRight, Backpack, Box, Castle, Check, ChevronRight, CircleHelp, Coins, Compass, Crosshair, Flag, Gem, Hammer, Heart, Home, LockKeyhole, Maximize, Mountain, Pause, Pickaxe, Play, Plus, RotateCcw, Settings2, Shield, ShieldCheck, Skull, Sparkles, Sprout, Sword, Target, Tent, TreePine, Trees, Users, Volume2, VolumeX, Wind, X, Zap, type LucideIcon } from 'lucide-react';
import { BALANCE, LEVELS, REGIONS, RESOURCE_NAMES, WEAPON_STAGES, ROUTES, UPGRADES, type UpgradeId } from './game/data';
import { baseMaxHp, buildSecondBase, buyEquipment, buySkill, buyUpgrade, skillCost, equipmentCap, equipmentCost, loadSave, supplyAttackBonus, upgradeCost, upgradeLevel, upgradeLock, type EquipmentSlot } from './game/state';
import { Game } from './game/engine';
import { drawMinimap, render } from './game/render';
import { sfx } from './game/audio';

type Modal = 'world' | 'equipment' | 'settings' | 'help' | null;
const icons: Record<string, LucideIcon> = { sword: Sword, zap: Zap, target: Target, heart: Heart, wind: Wind, users: Users, shield: Shield, wall: Castle, tower: Flag, crosshair: Crosshair, box: Box, hammer: Hammer, home: Home };
const fmt = (v: number) => Math.floor(v).toLocaleString('ja-JP');
const timer = (v: number) => `${Math.floor(Math.max(0, v) / 60)}:${String(Math.floor(Math.max(0, v) % 60)).padStart(2, '0')}`;

export default function App() {
  const [, rerender] = useState(0); const [notices, setNotices] = useState<{ id: number; text: string }[]>([]);
  const [modal, setModal] = useState<Modal>(null); const [buildTab, setBuildTab] = useState('hero'); const [region, setRegion] = useState(1); const [resetConfirm, setResetConfirm] = useState(false);
  const gameRef = useRef<Game | null>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const miniRef = useRef<HTMLCanvasElement>(null); const stageRef = useRef<HTMLDivElement>(null); const stickRef = useRef<HTMLDivElement>(null); const [stick, setStick] = useState({ x: 0, y: 0 });
  if (!gameRef.current) gameRef.current = new Game(loadSave(), () => {}, () => {});
  const g = gameRef.current, s = g.save, base = g.base, stats = g.stats;
  sfx.configure(s.settings.sfxVolume, s.settings.sfxMuted);
  g.onChange = () => rerender(n => n + 1);
  g.notify = text => setNotices(old => [...old.slice(-2), { id: Date.now() + Math.random(), text }]);
  g.overlay = modal !== null;
  useEffect(() => {
    let handle = 0; let last = performance.now();
    const animate = (now: number) => {
      g.update((now - last) / 1000); last = now;
      const canvas = canvasRef.current;
      if (canvas) { const rect = canvas.getBoundingClientRect(), dpr = Math.min(2, window.devicePixelRatio || 1); if (canvas.width !== Math.round(rect.width * dpr) || canvas.height !== Math.round(rect.height * dpr)) { canvas.width = Math.round(rect.width * dpr); canvas.height = Math.round(rect.height * dpr); } const ctx = canvas.getContext('2d'); if (ctx) { ctx.setTransform(dpr, 0, 0, dpr, 0, 0); render(ctx, g, rect.width, rect.height); } }
      const mini = miniRef.current?.getContext('2d'); if (mini) drawMinimap(mini, g);
      handle = requestAnimationFrame(animate);
    };
    handle = requestAnimationFrame(animate);
    const down = (e: KeyboardEvent) => { if ((e.target as HTMLElement)?.matches('input, select, textarea')) return; const key = e.key.toLowerCase(); if (key === 'escape') { if (g.overlay) setModal(null); else { g.paused = !g.paused; g.onChange(); } return; } if (g.overlay) return; if ([' ', 'arrowup', 'arrowdown', 'arrowleft', 'arrowright'].includes(key)) e.preventDefault(); if (e.repeat) return; g.keys.add(key); if (key === ' ') g.dash(); if (key === 'q') g.skill(); if (key === 'r') g.heal(); if (key === 'e') g.interact(); };
    const up = (e: KeyboardEvent) => g.keys.delete(e.key.toLowerCase());
    const blur = () => { g.keys.clear(); g.joystick = { x: 0, y: 0 }; setStick({ x: 0, y: 0 }); g.paused = true; g.persist(); };
    const visibility = () => { if (document.hidden) blur(); };
    const save = () => g.persist();
    window.addEventListener('keydown', down); window.addEventListener('keyup', up); window.addEventListener('blur', blur); document.addEventListener('visibilitychange', visibility); window.addEventListener('pagehide', save);
    return () => { cancelAnimationFrame(handle); window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); window.removeEventListener('blur', blur); document.removeEventListener('visibilitychange', visibility); window.removeEventListener('pagehide', save); };
  }, [g]);
  useEffect(() => { if (!notices.length) return; const t = setTimeout(() => setNotices(old => old.slice(1)), 6500); return () => clearTimeout(t); }, [notices]);
  useEffect(() => { if (!modal) return; const el = document.querySelector<HTMLElement>('.modal'); const before = document.activeElement as HTMLElement; el?.focus(); const trap = (event: KeyboardEvent) => { if (event.key !== 'Tab') return; const list = el?.querySelectorAll<HTMLElement>('button:not(:disabled), input, a[href], [tabindex="0"]'); if (!list?.length) return; const first = list[0], last = list[list.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', trap); return () => { document.removeEventListener('keydown', trap); before?.focus(); }; }, [modal]);
  const open = (name: Modal) => { g.keys.clear(); g.joystick = { x: 0, y: 0 }; setStick({ x: 0, y: 0 }); setModal(name); };
  const purchase = (id: UpgradeId) => { if (buyUpgrade(s, id)) { sfx.play(['soldiers', 'wall', 'tower', 'cannon', 'healer', 'storage', 'forge', 'base'].includes(id) ? 'build' : 'upgrade'); g.emit(`${UPGRADES.find(u => u.id === id)!.name}を強化しました`); g.persist(); } else sfx.play('error'); };
  const stickMove = (e: ReactPointerEvent<HTMLDivElement>) => { const rect = stickRef.current!.getBoundingClientRect(); const dx = e.clientX - rect.left - rect.width / 2, dy = e.clientY - rect.top - rect.height / 2; const length = Math.hypot(dx, dy); const radius = 34; const pos = { x: dx / Math.max(radius, length), y: dy / Math.max(radius, length) }; g.joystick = pos; setStick({ x: pos.x * radius, y: pos.y * radius }); };
  const regionData = REGIONS[region]; const activeRegion = REGIONS[g.region];
  const skillPrice = skillCost(s);
  const weaponStage = WEAPON_STAGES.filter(stage => stage.rank <= s.equipment.weapon).at(-1)!;
  const nextWeaponStage = WEAPON_STAGES.find(stage => stage.rank > s.equipment.weapon);
  const phaseLabel = g.endless ? (g.endless === 'defense' ? 'エンドレス防衛' : 'エンドレス遠征') : g.mode === 'expedition' ? '遠征中' : g.waveActive ? '防衛戦' : '準備フェーズ';
  const mission = g.endless ? (g.endless === 'defense' ? '拠点を守り、5Waveごとの主を倒そう' : g.bossDefeated ? '危険度クリア！ 次へ進むか報酬を持ち帰ろう' : `敵を倒して主を誘い出そう ${Math.min(g.expeditionKills, g.bossTarget)} / ${g.bossTarget}`) : !s.expeditionUnlocked ? base.wave < 2 ? '3ウェーブを突破し、遠征への道を開こう' : '草原の主を倒して、世界へ踏み出そう' : g.mode === 'expedition' ? g.bossDefeated ? s.completed ? s.level === 55 ? '本編クリア！ 拠点へ帰還して「果てなき地平」へ' : '本編クリア！ Lv55で「果てなき地平」が解禁' : '地域の主を討伐済み。発見と資源を持ち帰ろう' : `敵を倒して地域の主を誘い出そう ${Math.min(g.expeditionKills, 14)} / 14` : s.completed ? s.level === 55 ? '「果てなき地平」解禁！ 上のパネルからエンドレスへ' : '最終ボス討伐済み。Lv55で「果てなき地平」が解禁' : '拠点を育てて、まだ見ぬ地平へ';
  const upgradeIds = buildTab === 'hero' ? ['attack', 'speed', 'range', 'health', 'move'] : buildTab === 'army' ? ['soldiers', 'training', 'tower', 'cannon'] : ['base', 'wall', 'healer', 'storage', 'forge'];
  return <div className="app-shell" onPointerDownCapture={event => { sfx.unlock(); const button = (event.target as HTMLElement).closest('button'); if (!button) return; if (button.disabled || button.getAttribute('aria-disabled') === 'true') sfx.play('error'); else if (!button.matches('.upgrade-buy, .equipment-card button, .skill-upgrade button, .second-base button, .endless-forge button')) sfx.play('confirm'); }}>
    <header className="header">
      <a href="#" className="brand" onClick={e => e.preventDefault()} aria-label="OUTPOST 野営地と遠い地平"><span className="brand-mark"><Mountain size={27}/></span><span>OUTPOST<small>野営地と遠い地平</small></span></a>
      <nav className="main-nav"><button className={g.mode === 'base' ? 'active' : ''} onClick={() => { if (g.mode === 'expedition') g.returnHome(); }}><Tent size={17}/>拠点<span className="nav-dot"/></button><button className={g.mode === 'expedition' ? 'active' : ''} onClick={() => open('world')}><Compass size={17}/>遠征マップ</button><button onClick={() => open('equipment')}><Backpack size={17}/>装備・スキル</button></nav>
      <div className="top-resources"><span className="gold" title="コイン"><Coins size={18}/><b>{fmt(s.gold)}</b><small>コイン</small></span><span title="木材" aria-label={`木材 ${fmt(s.materials.wood)}`}><TreePine size={17}/><b>{fmt(s.materials.wood)}</b></span><span title="鉄鉱石" aria-label={`鉄鉱石 ${fmt(s.materials.iron)}`}><Pickaxe size={17}/><b>{fmt(s.materials.iron)}</b></span><span title="結晶" aria-label={`結晶 ${fmt(s.materials.crystal)}`}><Gem size={17}/><b>{fmt(s.materials.crystal)}</b></span><button className="icon-btn" onClick={() => open('settings')} aria-label="設定"><Settings2 size={18}/></button></div>
    </header>
    <div className="mobile-resource-bar" aria-label="所持素材"><span><TreePine size={13}/>木材 <b>{fmt(s.materials.wood)}</b></span><span><Pickaxe size={13}/>鉄 <b>{fmt(s.materials.iron)}</b></span><span><Gem size={13}/>結晶 <b>{fmt(s.materials.crystal)}</b></span></div>

    <main>
      <div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> CHAPTER {String(Math.max(...s.visited, 0) + 1).padStart(2, '0')} <span className="heading-line"/> A PLACE TO CALL HOME</div><h1>{g.mode === 'base' ? base.name : activeRegion.name}<span>{g.mode === 'base' ? 'あなたの冒険は、ここから。' : activeRegion.sub}</span></h1></div><div className="heading-actions"><span className="saved"><span/> {g.saveError ? '保存できません' : `自動セーブ${g.savedAt ? ` ${g.savedAt}` : '有効'}`}</span><button className="subtle-btn" onClick={() => open('help')}><CircleHelp size={16}/><span>遊び方</span></button></div></div>

      {s.raidPending && <div className="raid-alert"><Shield size={19}/><strong>拠点に襲撃の予兆</strong><span>帰還まで {timer(s.raidTime)} — 防衛に加勢しましょう</span><button onClick={() => g.mode === 'expedition' ? g.returnHome() : g.startWave()}>防衛する <ArrowRight size={15}/></button></div>}

      <EndlessPanel game={g}/>
      <div className="game-layout">
        <section className="play-panel">
          <div className="scene-bar"><div><span className={`phase-dot ${g.waveActive ? 'battle' : ''}`}/><b>{phaseLabel}</b><span className="scene-divider"/><span>{g.endless ? `${g.endless === 'defense' ? 'WAVE' : '危険度'} ${g.endlessRound} · 敵 Lv.${g.danger}` : g.mode === 'base' ? `WAVE ${String(base.wave + 1).padStart(2, '0')}` : `推奨 Lv.${activeRegion.min}–${activeRegion.max}`}</span>{!g.endless && g.mode === 'base' && <small>{(base.wave + 1) % 3 === 0 ? 'BOSS WAVE' : `危険度 Lv.${g.danger}`}</small>}</div><div><span className="scene-weather"><span>☀</span> 穏やかな昼</span><button className="icon-btn" aria-label={g.paused ? '再開' : '一時停止'} onClick={() => { g.paused = !g.paused; g.onChange(); }}>{g.paused ? <Play size={15}/> : <Pause size={15}/>}</button><button className="icon-btn fullscreen-button" aria-label="ゲーム画面を全画面にする" onClick={() => { if (document.fullscreenElement) void document.exitFullscreen(); else void stageRef.current?.requestFullscreen().catch(() => g.emit('このブラウザでは全画面表示を利用できません')); }}><Maximize size={15}/></button></div></div>
          <div className="game-stage" ref={stageRef}>
            <canvas className="game-canvas" ref={canvasRef} aria-label="見下ろし型の戦場。WASDで移動、自動攻撃、Qで範囲攻撃、Spaceで回避" tabIndex={0} onPointerDown={e => e.currentTarget.focus()}/>
            <div className="hero-hud"><div className="hero-portrait"><span/><Sword size={22}/><b>{s.level}</b></div><div className="hero-vitals"><div><strong>旅人</strong><span>Lv.{s.level} <span className="muted">/ 55</span></span></div><div className="health-track"><i style={{ width: `${Math.max(0, g.hero.hp / stats.hp * 100)}%` }}/><span><Heart size={10}/> {Math.ceil(g.hero.hp)} / {stats.hp}</span></div><div className="xp-track" role="progressbar" aria-label="経験値" aria-valuenow={s.xp} aria-valuemax={LEVELS[s.level - 1].xp || 1} title={`EXP ${s.xp} / ${LEVELS[s.level - 1].xp || 'MAX'}`}><i style={{ width: `${s.level === 55 ? 100 : s.xp / LEVELS[s.level - 1].xp * 100}%` }}/></div></div></div>
            <div className="minimap"><div><span>N</span><Compass size={10}/></div><canvas ref={miniRef} width={120} height={120} aria-label="ミニマップ。黄緑が主人公、赤が敵、黄が発見地点"/><small>{g.mode === 'base' ? base.name : activeRegion.name}</small></div>
            <div className="scene-location"><span>{g.mode === 'base' ? 'GREENWIND OUTPOST' : activeRegion.sub}</span><b>{g.mode === 'base' ? '小さな灯り、大きな旅。' : '知らない道の、その先へ。'}</b></div>
            {g.mode === 'expedition' && activeRegion.min > s.level + 4 && <div className="danger-badge"><Skull size={15}/> 危険度：極めて高い · 推奨 Lv.{activeRegion.min}+</div>}
            {g.enemies.find(e => e.kind === 'boss') && <div className="boss-hud"><span><Skull size={14}/>{g.endless === 'defense' ? '果てなき地平の主' : g.mode === 'base' ? '草原の主' : activeRegion.boss}</span><div><i style={{ width: `${g.enemies.find(e => e.kind === 'boss')!.hp / g.enemies.find(e => e.kind === 'boss')!.maxHp * 100}%` }}/></div></div>}
            <div className="field-notices" aria-live="polite">{notices.map(n => <div key={n.id}><Sparkles size={14}/>{n.text}<button aria-label="通知を閉じる" onClick={() => setNotices(old => old.filter(a => a.id !== n.id))}><X size={12}/></button></div>)}</div>
            {g.nearestPoint && <button className="interact-button" onClick={() => g.interact()}><kbd>E</kbd>{g.nearestPoint.label}<ChevronRight size={15}/></button>}
            <div className="joystick" ref={stickRef} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); stickMove(e); }} onPointerMove={e => { if (e.currentTarget.hasPointerCapture(e.pointerId)) stickMove(e); }} onPointerUp={() => { g.joystick = { x: 0, y: 0 }; setStick({ x: 0, y: 0 }); }} onPointerCancel={() => { g.joystick = { x: 0, y: 0 }; setStick({ x: 0, y: 0 }); }}><div className="stick-directions">＋</div><div className="stick-thumb" style={{ transform: `translate(${stick.x}px, ${stick.y}px)` }}/></div>
            <div className="skillbar"><SkillButton icon={Wind} name="回避" hotkey="SPACE" cooldown={g.hero.dash} onClick={() => g.dash()}/><SkillButton icon={Zap} name="旋風撃" hotkey="Q" cooldown={g.hero.skill} onClick={() => g.skill()} primary/><SkillButton icon={Heart} name="回復" hotkey="R" cooldown={g.hero.potion} onClick={() => g.heal()}/></div>
            {g.paused && <div className="pause-screen"><Pause size={30}/><h2>ひと休み。</h2><p>冒険は、あなたのペースで。</p><button className="primary-btn" onClick={() => { g.paused = false; g.onChange(); }}><Play size={16}/>冒険を再開</button></div>}
          </div>
          <div className="supply-strip"><Box size={13}/><b>遠征補給 {s.supplies} / {BALANCE.progression.supplyCap}</b><span>{g.endless === 'defense' ? '防衛報酬：コイン・素材・超越の欠片' : g.mode === 'expedition' ? g.prepared ? '補給効果 発動中' : '補給なしで探索中' : `防衛成功で +${BALANCE.progression.supplyReward}。遠征1回につき1個使用`}</span></div>
          <div className="mission-bar"><div className="mission-icon"><Flag size={19}/></div><div><small>CURRENT OBJECTIVE</small><strong>{mission}</strong></div>{g.mode === 'base' ? <button className="primary-btn" disabled={g.waveActive} onClick={() => g.startWave()}>{g.waveActive ? `残り ${g.enemies.length + g.spawnLeft} 体` : '防衛を開始'}{g.waveActive ? <Shield size={16}/> : <ArrowRight size={16}/>}</button> : <button className="primary-btn" onClick={() => g.returnHome()}><Home size={16}/>拠点に帰還</button>}</div>
          <div className="keyboard-hints"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> 移動</span><span><Crosshair size={12}/> 攻撃は自動</span><span><kbd>SPACE</kbd> 回避</span><span><kbd>Q</kbd> スキル</span><span><kbd>E</kbd> 調べる</span><span className="pause-hint"><kbd>ESC</kbd> 一時停止</span></div>
        </section>

        <aside className="upgrade-panel"><div className="panel-title"><div className="panel-icon"><Hammer size={19}/></div><div><h2>拠点を育てる</h2><p>小さな積み重ねが、力になる。</p></div><span className="base-level">Lv.{base.upgrades.base + 1}</span></div>
          <div className="base-integrity"><div><span><ShieldCheck size={13}/>拠点の耐久力</span><b>{Math.ceil(base.hp)} <small>/ {baseMaxHp(base)}</small></b></div><div className="integrity-track"><i style={{ width: `${base.hp / baseMaxHp(base) * 100}%` }}/></div><div className="garrison"><span><Users size={12}/>守備隊 <b>{base.upgrades.soldiers} 人</b></span><span>防衛成功 <b>{base.wave} 回</b></span></div></div>
          <div className="build-tabs">{[['hero', '主人公', Sword], ['army', '兵士・防衛', Shield], ['base', '施設', Home]].map(([key, title, Icon]) => { const TabIcon = Icon as LucideIcon; return <button key={key as string} className={buildTab === key ? 'selected' : ''} onClick={() => setBuildTab(key as string)}><TabIcon size={14}/>{title as string}</button>; })}</div>
          <div className="upgrade-list">{UPGRADES.filter(u => upgradeIds.includes(u.id)).map(u => { const cost = upgradeCost(s, u.id), lv = upgradeLevel(s, u.id), lock = upgradeLock(s, u.id), Icon = icons[u.icon]; const afford = s.gold >= cost.gold && (!cost.material || s.materials[cost.material] >= cost.count); return <div className={`upgrade-row ${lock ? 'locked' : ''}`} key={u.id}><div className="upgrade-icon"><Icon size={20}/></div><div className="upgrade-info"><h3>{u.name}<span>Lv.{lv}</span></h3><p>{lock || u.desc}</p><small><Coins size={11}/>{fmt(cost.gold)}{cost.material && <><span> · </span>{RESOURCE_NAMES[cost.material]} {cost.count}</>}</small></div><button className="upgrade-buy" disabled={!!lock || !afford || g.mode !== 'base'} onClick={() => purchase(u.id)} onPointerDown={() => { if (lock || !afford || g.mode !== 'base') sfx.play('error'); }} aria-label={`${u.name}を強化 ${cost.gold}コイン`} title={g.mode !== 'base' ? '拠点への帰還が必要' : lock || '強化する'}>{lock ? <LockKeyhole size={14}/> : <Plus size={18}/>}</button></div>; })}</div>
          <div className="upgrade-tip"><Sprout size={17}/><p>{g.mode === 'expedition' ? '強化は拠点への帰還後に行えます。集めた素材は自動で保存されます。' : buildTab === 'hero' ? 'まずは攻撃力を強化。敵を倒してコインを集めよう。' : '遠征で設計図や生存者を見つけると、新しい仲間と施設が解禁されます。'}</p></div>
          <button className="equipment-link" onClick={() => open('equipment')}><Backpack size={17}/>装備とスキルを確認<ArrowRight size={16}/></button>
        </aside>
      </div>

      <section className="journey-section"><div className="section-heading"><div><Compass size={19}/><h2>地平の向こうへ</h2><span>BEYOND THE OUTPOST</span></div><button onClick={() => open('world')}>ワールドマップを開く <ArrowRight size={15}/></button></div><div className="journey-grid">
        {[REGIONS[1], REGIONS[3], REGIONS[5]].map((r, i) => { const Icon = [Trees, Mountain, Flag][i]; return <button className={`region-card region-${i}`} key={r.id} onClick={() => { setRegion(r.id); open('world'); }}><div className="landscape"><Landscape type={i}/></div><div className="region-card-content"><span className="region-level">Lv.{r.min}–{r.max}</span><h3>{r.name}</h3><p><Icon size={12}/>{['木材と、まだ見ぬ仲間', '鉄鉱石と、眠れる技術', '新しい拠点への第一歩'][i]}</p></div><span className="region-arrow"><ArrowRight size={17}/></span></button>; })}
      </div></section>
      <footer><span><Mountain size={14}/> OUTPOST <span className="footer-separator">/</span> 小さな拠点から、遠い地平へ。</span><span><span className="live-dot"/> LOCAL SAVE <span className="footer-separator">·</span> Lv.1—55 <span className="footer-separator">·</span> 11 REGIONS</span></footer>
    </main>

    {modal && <div className="modal-backdrop" onPointerDown={e => { if (e.target === e.currentTarget) open(null); }}><section className={`modal ${modal === 'world' ? 'world-modal' : ''}`} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-heading"><div><div className="eyebrow">{modal === 'world' ? 'CHOOSE YOUR OWN PATH' : modal === 'equipment' ? 'PREPARE FOR THE UNKNOWN' : 'YOUR ADVENTURE'}</div><h2 id="modal-title">{modal === 'world' ? 'まだ見ぬ地平へ' : modal === 'equipment' ? '装備とスキル' : modal === 'settings' ? '冒険の設定' : '旅人の手引き'}</h2></div><button className="icon-btn" onClick={() => open(null)} aria-label="閉じる"><X size={21}/></button></div>
      {modal === 'world' && <><p className="modal-intro">行き先は、あなた次第。すべての地域に入れますが、格上の敵は非常に危険です。</p><div className="world-content"><div className="world-map"><div className="map-compass">N<Compass size={34}/><small>THE KNOWN WORLD</small></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="map-routes">{ROUTES.map(([a, b]) => <line key={`${a}-${b}`} x1={REGIONS[a].x} y1={REGIONS[a].y} x2={REGIONS[b].x} y2={REGIONS[b].y} stroke={s.visited.includes(a) && s.visited.includes(b) ? '#b9d98b' : '#9cad8e55'} strokeWidth=".35" strokeDasharray="1 1.2"/>)}</svg>{REGIONS.map(r => <button key={r.id} className={`map-node ${region === r.id ? 'selected' : ''} ${s.bosses.includes(r.id) ? 'cleared' : ''}`} style={{ left: `${r.x}%`, top: `${r.y}%`, '--region-color': r.color } as React.CSSProperties} onClick={() => setRegion(r.id)}><span>{s.bosses.includes(r.id) ? <Check size={14}/> : r.id === 0 ? <Tent size={16}/> : r.id === 10 ? <Skull size={16}/> : <Mountain size={15}/>}</span><b>{r.name}</b><small>Lv.{r.min}–{r.max}</small></button>)}<div className="map-legend"><span><i/>未踏の地域</span><span><i/>選択中</span><span><Check size={10}/>ボス討伐済</span></div></div>
      <div className="region-detail"><span className="eyebrow">REGION {String(region + 1).padStart(2, '0')}</span><h3>{regionData.name}</h3><div className={`danger-level ${regionData.min > s.level + 4 ? 'high' : ''}`}><Skull size={16}/>推奨 Lv.{regionData.min}–{regionData.max}<b>{regionData.min > s.level + 4 ? '極めて危険' : regionData.min > s.level ? '挑戦' : '探索に適正'}</b></div><p>この地の発見で「{regionData.unlock}」を獲得できます。道を外れ、資源と宝箱を探しましょう。</p><div className="region-detail-row"><Gem size={16}/><span>主な資源</span><b>{RESOURCE_NAMES[regionData.resource]}</b></div><div className="region-detail-row"><Skull size={16}/><span>地域の主</span><b>{regionData.boss}</b></div><div className="discovery-box"><Sparkles size={18}/><div><small>この地域の発見</small><strong>{regionData.event}</strong><p>{s.discoveries.includes(region) ? '✓ 発見済み — ' : ''}{regionData.unlock}</p></div></div><p className="map-tip">黄色の点は発見・宝箱。守護エリートを倒して近づき、Eで調べます。14体倒すとボスが出現。</p><div className="supply-plan"><Box size={15}/><span>{s.supplies > 0 ? `補給使用：攻撃 +${Math.round(supplyAttackBonus(s) * 100)}%・経験値 +20%・被ダメージ −12%` : '補給なし。防衛に成功すると次の遠征を有利にできます。'}</span></div><button className="primary-btn travel-btn" disabled={!!g.endless || !s.expeditionUnlocked || g.waveActive || s.raidPending} onClick={() => { if (g.travel(region)) open(null); }}><Compass size={17}/>{!s.expeditionUnlocked ? '防衛3ウェーブ突破で解放' : g.waveActive ? '防衛戦を終えてから出発' : s.raidPending ? '襲撃への対応が必要' : 'この地域へ遠征'}<ArrowRight size={16}/></button><small className="travel-note">レベルによる入場制限はありません</small></div></div>
      <div className="second-base"><Tent size={22}/><div><strong>赤砂の前哨基地</strong><p>{s.bases.length > 1 ? '恒久強化は共通。施設の建設費は28%軽減されます。' : '荒野で高台を発見すると、第二拠点を建設できます。600コイン / 鉄35'}</p></div><button className="subtle-btn" disabled={!!g.endless || g.waveActive || g.mode !== 'base' || s.raidPending || (s.bases.length < 2 && (!s.discoveries.includes(5) || s.gold < BALANCE.secondBase.gold || s.materials.iron < BALANCE.secondBase.iron))} onClick={() => { if (s.bases.length < 2) { if (buildSecondBase(s)) { sfx.play('build'); g.emit('第二拠点を建設しました'); } else sfx.play('error'); } else { s.activeBase = s.activeBase === 0 ? 1 : 0; g.makeWorld(); g.emit(`${g.base.name}へ移動しました`); } g.persist(); }}>{s.bases.length > 1 ? s.activeBase === 0 ? '第二拠点へ' : '第一拠点へ' : '建設する'}</button></div></>}
      {modal === 'equipment' && <><div className="equipment-stats"><span>Lv.<b>{s.level}</b><small>経験値 {fmt(s.xp)} / {s.level === 55 ? 'MAX' : fmt(LEVELS[s.level - 1].xp)}</small></span><span><Sword size={17}/><b>{Math.round(stats.attack)}</b><small>攻撃力</small></span><span><Heart size={17}/><b>{stats.hp}</b><small>最大HP</small></span><span><Target size={17}/><b>{stats.range}</b><small>射程</small></span></div><p className="modal-intro">強い装備は自動装備。鍛造でも強化できます。鉱山で+12、山岳で+14、廃都市で+18まで鍛造できます。</p><div className="equipment-grid">{(['weapon', 'armor', 'charm'] as EquipmentSlot[]).map((slot, i) => { const lv = s.equipment[slot], resource = lv >= 12 ? 'crystal' : lv >= 4 ? 'iron' : 'wood'; const Icon = [Sword, Shield, Gem][i]; return <div className="equipment-card" key={slot}><span className="eyebrow">{['WEAPON', 'ARMOR', 'ACCESSORY'][i]}</span><Icon size={36}/><h3>{[weaponStage.name, '野営の外套', '地平の護符'][i]} <span>+{lv}</span></h3><p>{['攻撃力', '最大HP', '会心率・経験値'][i]} +{i === 2 ? `${(lv * 1.8).toFixed(1)}% / ${(lv * 3.5).toFixed(1)}%` : `${lv * (i === 0 ? 16 : 13)}%`}</p><small><Coins size={12}/>{fmt(equipmentCost(s, slot))} · {RESOURCE_NAMES[resource]} {4 + lv * 2}</small><button className="subtle-btn" disabled={g.mode !== 'base' || lv >= equipmentCap(s) || s.gold < equipmentCost(s, slot) || s.materials[resource] < 4 + lv * 2} onClick={() => { if (buyEquipment(s, slot)) { sfx.play('upgrade'); g.emit('装備を鍛造しました'); g.persist(); } else sfx.play('error'); }}><Hammer size={14}/>{lv >= equipmentCap(s) ? '現在の鍛造上限' : '装備を鍛造'}</button></div>; })}</div><p className="armor-note">防具の節目補正：被ダメージ −{Math.round(stats.damageReduction * 100)}%。防具+6・+12・+18で段階的に向上します。</p><div className="weapon-milestone"><Sparkles size={19}/><div><strong>{weaponStage.name} — 節目補正 ×{(1 + Math.floor(s.equipment.weapon / BALANCE.progression.weaponMilestone) * BALANCE.progression.weaponMilestoneBonus).toFixed(2)}</strong><p>{nextWeaponStage ? `次は武器 +${nextWeaponStage.rank}「${nextWeaponStage.name}」。最終攻撃倍率がさらに上がります。` : '最終覚醒に到達。身につけた力で、終焉の要塞へ。'}</p></div></div><div className="skill-upgrade"><div className="upgrade-icon"><Zap size={22}/></div><div><h3>旋風撃 <span>Lv.{s.skill + 1}</span></h3><p>周囲に攻撃力の{Math.round((BALANCE.skillDamage + s.skill * BALANCE.skillUpgrade.damage) * 100)}%ダメージ。強化で威力と回転率が上昇。</p><small>費用 {fmt(skillPrice.gold)} コイン {skillPrice.crystal ? ` / 結晶 ${skillPrice.crystal}` : ''}</small></div><button className="subtle-btn" disabled={g.mode !== 'base' || s.skill >= BALANCE.skillUpgrade.max || s.gold < skillPrice.gold || s.materials.crystal < skillPrice.crystal} onClick={() => { if (buySkill(s)) { sfx.play('upgrade'); g.emit('旋風撃を強化しました'); g.persist(); } else sfx.play('error'); }}>{s.skill >= BALANCE.skillUpgrade.max ? 'MAX' : '強化'}</button></div><div className="inventory-line"><Box size={16}/><b>所持素材</b><span>木材 {fmt(s.materials.wood)}</span><span>鉄鉱石 {fmt(s.materials.iron)}</span><span>結晶 {fmt(s.materials.crystal)}</span></div></>}
      {modal === 'settings' && <><p className="modal-intro">設定画面やマップを開いている間、ゲームの時間は止まります。</p>{([['particles', 'エフェクト表示', '攻撃とレベルアップの演出'], ['shake', '画面の揺れ', 'ダメージを受けたときの軽い振動']] as const).map(([key, name, desc]) => <div className="setting-row" key={key}><div><strong>{name}</strong><p>{desc}</p></div><button className={`toggle ${s.settings[key] ? 'on' : ''}`} role="switch" aria-checked={s.settings[key]} aria-label={name} onClick={() => { s.settings[key] = !s.settings[key]; g.persist(); }}><span/></button></div>)}<div className="setting-row sound-setting"><div><strong>効果音</strong><p>Web Audio APIで生成した、軽く落ち着いたSEです。</p><label><span>音量 {Math.round(s.settings.sfxVolume * 100)}%</span><input type="range" min="0" max="100" step="5" value={Math.round(s.settings.sfxVolume * 100)} aria-label="効果音の音量" disabled={s.settings.sfxMuted} onChange={event => { s.settings.sfxVolume = Number(event.target.value) / 100; sfx.configure(s.settings.sfxVolume, s.settings.sfxMuted); sfx.play('confirm'); g.persist(); g.onChange(); }}/></label></div><button className={`sound-mute ${s.settings.sfxMuted ? 'muted' : ''}`} role="switch" aria-checked={!s.settings.sfxMuted} aria-label="効果音をミュート" onClick={() => { s.settings.sfxMuted = !s.settings.sfxMuted; sfx.configure(s.settings.sfxVolume, s.settings.sfxMuted); if (!s.settings.sfxMuted) sfx.play('confirm'); g.persist(); }}>{s.settings.sfxMuted ? <VolumeX size={18}/> : <Volume2 size={18}/>}<span>{s.settings.sfxMuted ? 'ミュート中' : '再生中'}</span></button></div><div className="setting-row"><div><strong>セーブデータ</strong><p>約8秒ごとに、このブラウザへ自動保存します。</p></div><button className="subtle-btn" onClick={() => { g.persist(); g.emit(g.saveError ? '保存に失敗しました。ブラウザのストレージ設定を確認してください' : '冒険の記録を保存しました'); }}><ArrowDownToLine size={15}/>今すぐ保存</button></div><div className="reset-box"><div><strong>新しい冒険を始める</strong><p>レベル、装備、拠点を含むすべての進行を消去します。</p></div>{resetConfirm ? <div className="reset-actions"><button className="danger-btn" onClick={() => { g.reset(); setResetConfirm(false); open(null); }}>記録を消去して開始</button><button className="subtle-btn" onClick={() => setResetConfirm(false)}>キャンセル</button></div> : <button className="subtle-btn" onClick={() => setResetConfirm(true)}><RotateCcw size={14}/>リセット</button>}</div></>}
      {modal === 'help' && <><div className="help-loop"><span><Shield size={23}/>守る</span><ChevronRight/><span><Hammer size={23}/>育てる</span><ChevronRight/><span><Compass size={23}/>旅する</span><ChevronRight/><span><Gem size={23}/>持ち帰る</span></div><div className="help-content"><h3>01 — まずは、家を守ろう</h3><p>「防衛を開始」で四方から敵が出現。射程内の敵へ自動で攻撃します。コインで攻撃力を強化し、3ウェーブ目のボスを倒すと遠征が解放されます。準備中は家の近くで全回復できます。</p><h3>02 — 操作と戦い方</h3><p>WASD / 矢印キーで移動。Spaceで無敵回避、Qで範囲攻撃、Rで回復、Eで採取・調査。スマホは左下のスティックと右下のボタンで操作します。赤い攻撃予兆を避けながら戦いましょう。</p><h3>03 — 好きな道へ進もう</h3><p>遠征の全11地域はレベル制限なし。Lv8でもLv20地域に入れますが、格上の攻撃は致命的です。弱い敵から経験値・装備を集め、敵を14体倒してボスに挑戦。宝箱や発見は守護エリートを倒してEで調べます。</p><h3>04 — 発見が、拠点を変える</h3><p>森の設計図で弓塔、鉱山の鉄で鍛冶屋、山岳で砲台が解禁。生存者救出で雇用枠が増えます。兵士・施設は雑魚に強く、エリートやボスには主人公が有効。荒野の高台を発見すれば第二拠点も建設できます。</p><h3>05 — 時々、帰る場所がある</h3><p>遠征解放後は約5分ごとに襲撃判定。守備隊が十分なら小規模襲撃を自動で撃退します。大規模襲撃は75秒の猶予後に緊急帰還。敵前哨地の制圧で間隔を延長できます（1地域25秒・合計200秒まで）。防衛報酬の補給は遠征の攻撃・経験値・耐久を強化します。戦闘不能でも失うのはコインの8%だけです。</p><h3>06 — Lv55、その先の地平へ</h3><p>終焉の要塞のボス討伐がクリア条件。Lv55と最終ボス討伐を両方達成すると「果てなき地平」が解禁。エンドレス防衛は5Waveごとにボス、遠征はボス討伐で次の危険度へ。欠片で超越鍛造を繰り返せます。進行はブラウザに自動保存。遠征中に終了すると拠点から再開し、進行中のウェーブは最初からになります。</p></div><button className="primary-btn" onClick={() => open(null)}>冒険を始めよう <ArrowRight size={16}/></button></>}
    </section></div>}
  </div>;
}

function SkillButton({ icon: Icon, name, hotkey, cooldown, onClick, primary = false }: { icon: LucideIcon; name: string; hotkey: string; cooldown: number; onClick: () => void; primary?: boolean }) { return <button className={`skill-button ${primary ? 'primary' : ''}`} disabled={cooldown > 0} onClick={onClick} aria-label={`${name} ${hotkey}`}><kbd>{hotkey}</kbd><Icon size={22}/><span>{cooldown > 0 ? `${cooldown.toFixed(1)}s` : name}</span></button>; }
function Landscape({ type }: { type: number }) { return <svg viewBox="0 0 320 160" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><linearGradient id={`land-${type}`} x1="0" y1="0" x2="1" y2="1"><stop stopColor={['#567761', '#747f75', '#b38e6e'][type]}/><stop offset="1" stopColor={['#2e493d', '#354c46', '#6e6750'][type]}/></linearGradient></defs><rect width="320" height="160" fill={`url(#land-${type})`}/><circle cx="242" cy="35" r="21" fill="#ece1b0" opacity=".25"/><path d="M0 89Q68 22 147 75T320 65V160H0" fill="#b9c3a0" opacity=".12"/><path d="M0 135Q86 76 170 114T320 100V160H0" fill="#263d31" opacity=".23"/>{type === 0 ? Array.from({ length: 10 }, (_, i) => <g key={i} transform={`translate(${160 + i * 19},${83 + i % 3 * 23})`} opacity={.3 + i % 3 * .15}><path d="M0 0 17-48 34 0Z" fill="#203f30"/><path d="M3-18 17-58 31-18Z" fill="#88a582"/><path d="M17 0v12" stroke="#b0b08a" strokeWidth="3"/></g>) : type === 1 ? <g><path d="m116 149 81-121 85 121" fill="#87958a"/><path d="m197 28 21 33-21-7-17 8Z" fill="#cdd1b5"/><path d="m211 152 50-89 60 89" fill="#617368"/><path d="m199 93 15 60h-38Z" fill="#283e37"/><path d="m175 151 5-60h32l9 60M179 104h35" stroke="#b1a685" strokeWidth="5" fill="none"/></g> : <g><path d="m161 144 19-61h43l28 61" fill="#b5a186"/><path d="m212 83 11 61h28l-28-61" fill="#8b7c65"/><path d="M265 116V42" stroke="#6a6953" strokeWidth="4"/><path d="m267 43 36 9-36 16" fill="#d0c398"/><path d="m95 158 9-47h25l17 47" fill="#bbaa87"/></g>}</svg>; }
